### ISSUE TITLE
Thanks!

### ISSUE THREAD

**Issue by coderschoolreview** [se7oluti0n/rbblog#1]
Hi Manh, 

Thanks for your submission! It is great to see that you continued improve your work over time.
## Great things:
- All the required features work well
- A clean routes.rb file
- The use of gem ''acts_as_commentable' for your optional feature 
## Suggestions:
- Please add your name and the app name in README
- You should have some validations in your model (title and body of article must be present or title is unique)
- Your search function could be shorter (1 line)

Just some feedbacks. Feel free to update your submission. We will make decision within 2 days. Once again, good work!

**Comment by se7oluti0n** [comment]
Hi, thank you for you review. I will continue updating my work.
